AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Template

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Description: Ambiente de deploy

Resources:
  MyLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "supabaseConnectorV2-${Environment}"
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 60

      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {
                  "statusCode": 200,
                  "body": "Hello World"
              }

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "supabaseConnectorV2-${Environment}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

Outputs:
  LambdaName:
    Value: !Ref MyLambda