name: AWS Test

on:
  push:
    branches: [feature/iotpipe]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Test AWS Connection
        run: aws sts get-caller-identity

      - name: test deploy read file.
        run: |
          aws s3 cp files/read.txt s3://jdf-data-lake-renan/new_deploy/read.txt

      - name: Deploy  Lambda lambda_name_here
        run: |
          echo "Deploying Stack for Lambda"

          aws cloudformation deploy \
            --stack-name supabase-connector-stack-dev \
            --template-file templates/supabaseConnectorV2.yml \
            --no-fail-on-empty-changeset \
            --parameter-overrides $(jq -r '.[] | [.ParameterKey,.ParameterValue] | join("=")' parameters/param-dev.json)

          # 2. Captura a variável ENVIRONMENT enquanto está no diretório raiz
          ENVIRONMENT=$(jq -r '.[] | select(.ParameterKey=="Environment") | .ParameterValue' parameters/param-dev.json)

          # 3. Compacta o arquivo apontando para o caminho correto na subpasta
          zip -j supabaseconnectorzip.zip scripts/supabase-connector/supabaseConnectorV2.py

          # 4. Atualiza o código da Lambda na AWS
          aws lambda update-function-code \
            --function-name supabaseConnectorV2-${ENVIRONMENT}-lf \
            --zip-file fileb://supabaseconnectorzip.zip