name: AWS Deploy - Dev

on:
  push:
    branches: [feature/iotpipe]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Deploy da infraestrutura (IaC) da Lambda 1: supabaseConnectorV2
      - name: Deploy Supabase Connector Stack (CloudFormation - dev)
        run: |
          aws cloudformation deploy --stack-name supabaseConnectorV2-dev-stack \
            --template-file templates/supabaseConnectorV2.yml --no-fail-on-empty-changeset \
            --parameter-overrides $(jq -r '.[] | [.ParameterKey, .ParameterValue] | "\(.[0])=\(.[1])"' parameters/param-dev.json ) \
            --capabilities CAPABILITY_NAMED_IAM
          cd scripts/supabase-connector/
          zip -r supconnector.zip .
          aws lambda update-function-code --function-name supabaseConnectorV2-dev --zip-file=fileb://supconnector.zip


      # Deploy da infraestrutura (IaC) da Lambda 2: telemetryEntryPointV2
      #- name: Deploy Telemetry Entry Point Stack (CloudFormation - dev)
      #  run: |
      #    PARAMS=$(jq -r '.[] | "\(.ParameterKey)=\(.ParameterValue)"' parameters/param-dev.json | tr '\n' ' ')
      #    aws cloudformation deploy \
      #      --stack-name telemetryEntryPointV2-dev \
      #      --template-file templates/telemetryEntryPointV2.yml \
      #      --parameter-overrides $PARAMS SnsTopicArn="${{ secrets.SNS_TOPIC_ARN }}" \

      # Deploy da Lambda 2: telemetryEntryPointV2
      #- name: Deploy Telemetry Entry Point Lambda
      #  run: |
      #    zip -j telemetry_lambda.zip scripts/telemetry-entry-point/telemetryEntryPointV2.py
      #    aws lambda update-function-code \
      #      --function-name telemetryEntryPointV2-dev \
      #      --zip-file fileb://telemetry_lambda.zip